### ISSUE TITLE
App Crashes when there is no Internet 

### ISSUE THREAD

**Issue by pritish12** [probelalkhan/android-mvvm-architecture#2]
App Crashes when there is no Internet

**Comment by KhanStan99** [comment]
@pritish12 This is fixed in [this video](https://www.youtube.com/watch?v=WddEJFYnELY) and fix is also updated in the latest code, You can close this issue.

**Comment by pritish12** [comment]
@KhanStan99 Try opening QuotesScreen with no Internet Connection. I have seen the video you mentioned and it only handles login and sign up screen when there is no internet

**Comment by KhanStan99** [comment]
@pritish12 Oh, i 'm still in #15 video, Didn't reached there yet.

**Comment by KhanStan99** [comment]
@pritish12 , I changed the code little bit and added exception handling in getQuotes API.

Instead of calling the lazy variable from quotes fragment, I created this function in QuotesViewModel:

`fun getAllQuotes() {
        Coroutines.main {
            try {
                val authResponse = repository.getQuotes()
                Log.e("Called", "Tick")
                quotesListener?.onSuccess(authResponse)
            } catch (e: ApiException) {
                quotesListener?.onFailure(e.message!!)
            } catch (e: NoInternetException) {
                quotesListener?.onFailure(e.message!!)
            }
        }
    }`

`quotesListener` is in interface just like authListener in LoginActivity and i initiated just like that in QuotesFragment. And Obviously you have to implement `QuotesListener` in QuotesFragment so you have to override all the interface methods (onfailure, onsucces and on started) so that you can do appropriate changes in UI.

**Comment by probelalkhan** [comment]
I have fixed this issue in the latest commit, check it. You can close the issue now. 
You just need to catch the exception while fetching the quotes. 

```
            try {
                val response = apiRequest { api.getQuotes() }
                quotes.postValue(response.quotes)
            } catch (e: Exception) {
                e.printStackTrace()
            }
```
